.github/workflows/host_dbt_docs/ci.yml
=> move to new folder

.github/workflows/host_dbt_docs.yml
Fixes/ Closes #8
* dbt version: (Run dbt --version, please include the plugin version also)
* …
=> Change folder name

.github/workflows/host_dbt_docs.yml
=> Change folder to save as artifacts

.github/workflows/host_dbt_docs.yml
=> Change artifact path and deploy folder

.github/workflows/host_dbt_docs.yml
=> add ls command to check linux dir

.github/workflows/host_dbt_docs.yml
=> update deploy folder

.github/workflows/host_dbt_docs.yml
=> test document ci build metadata

.github/workflows/host_dbt_docs.yml
=> Add shell as run step

.github/workflows/host_dbt_docs.yml
=> Update write file commands

.github/workflows/host_dbt_docs.yml
=> create folder before writing file

.github/workflows/host_dbt_docs.yml
=> Add os checking

.github/workflows/host_dbt_docs.yml
=> change os variable

.github/workflows/host_dbt_docs.yml
=> add if condition to check os type

.github/workflows/host_dbt_docs.yml
=> Remove shell argument

.github/workflows/host_dbt_docs.yml
=> Fix powershell utf8 problem

.github/workflows/host_dbt_docs.yml
=> Convert UTF8Bom file to utf8nobom

.github/workflows/host_dbt_docs.yml
=> Fix powershell syntax

.github/workflows/host_dbt_docs.yml
=> Parameterize dbt model name, schema

.github/workflows/host_dbt_docs.yml
=> change dbt model name scope to env

.github/workflows/host_dbt_docs.yml
=> Update env variable setup

.github/workflows/host_dbt_docs.yml
=> change inputs variable name

.github/workflows/host_dbt_docs.yml
=> Change env variable to uppercase

.github/workflows/host_dbt_docs.yml
=> Test capitalize env variable name

.github/workflows/host_dbt_docs.yml
=> Uncomment step to display env values

.github/workflows/host_dbt_docs.yml
=> Revamp create file step

.github/workflows/host_dbt_docs.yml
=> Remove print env step

.github/workflows/host_dbt_docs.yml
=> add more env environment to capture

.github/workflows/host_dbt_docs.yml
=> Create dbt profiles.yml on-the-fly

.github/workflows/host_dbt_docs.yml
=> Angan 8 change GitHub pages deploy action folder

.github/workflows/host_dbt_docs.yml
=> Change access method to env secrets

.github/workflows/host_dbt_docs.yml
=> display all env variables

.github/workflows/host_dbt_docs.yml
=> test echo secrets

.github/workflows/host_dbt_docs.yml
=> Test different method in accessing secret

.github/workflows/host_dbt_docs.yml
=> change secrets access method

.github/workflows/host_dbt_docs.yml
=> test create json workflow

.github/workflows/host_dbt_docs.yml
=> test marketplace workflow

.github/workflows/host_dbt_docs.yml
=> Test workflow

.github/workflows/host_dbt_docs.yml
=> Test repo secrets

.github/workflows/host_dbt_docs.yml
=> Requires secrets pass from caller

.github/workflows/host_dbt_docs.yml
=> Remove required input

.github/workflows/host_dbt_docs.yml
=> Required secret input

.github/workflows/host_dbt_docs.yml
=> Uncomment jobs

.github/workflows/host_dbt_docs.yml
=> Change artifact folder to upload

.github/workflows/host_dbt_docs.yml
=> disable checkout step

.github/workflows/host_dbt_docs.yml
=> enable checkout step

.github/workflows/host_dbt_docs.yml
=> Clean workflow file

.github/workflows/host_dbt_docs.yml
=> Update dbt profiles filename

.github/workflows/host_dbt_docs.yml
=> Print cwd recursively and specify working dir

.github/workflows/host_dbt_docs.yml
=> switch to PS syntax

.github/workflows/host_dbt_docs.yml
=> Change runner_type

.github/workflows/host_dbt_docs.yml
=> Skip steps when runner is Windows os

.github/workflows/host_dbt_docs.yml
=> bump actions/upload-artifact to v2

.github/workflows/host_dbt_docs.yml
=> bump actions/upload-artifact@v4

.env.sample, .github/workflows/host_dbt_docs.yml, readme.md, requirements.txt, script/99_set_env_base.bat, script/99_set_env_base.sh, script/conda/00_start_base_venv_miniconda_v1.bat, script/conda/00_start_venv_miniconda_v1.bat, script/conda/01_SSLError_troubleshoot.py, script/conda/01_create_conda_env_v1.bat, script/conda/02_pip_install_update_packages_v1.bat, script/conda/02_uv_install_update_packages_v1.bat, script/conda/03_remove_conda_env_v1.bat, script/conda/04_test_dbt_debug.bat, script/convert_eol_to_lf.py, script/create_folder_skeleton.bash, script/disable_lfs.bat, script/keyring/decrypt_env.bat, script/keyring/encrypt_env_base.py, script/keyring/get_key.py, script/keyring/inital_encrypt_env.bat, script/keyring/populate_env_enc.bat, script/keyring/readme.md, script/keyring/set_key.py, script/keyring/update_env_enc.bat, script/set_env_variables.bat, script/test.sh, start_github_action_runner.bat
=> Add support to windows self-hosted runner

.github/workflows/host_dbt_docs.yml
=> An 65 add support win self hosted runner

.github/workflows/host_dbt_docs.yml
=> add new scipt

upd_catalog_manifest.py
=> AN-PR-Add common dbt docs py script
